# Generated by Django 2.0.1 on 2018-04-06 13:34

import bukhach.utils.other_utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_avatar', models.ImageField(default='def_group_ava.jpeg', upload_to=bukhach.utils.other_utils.make_filepath, verbose_name='group_avatar')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='GroupInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_matched_date', models.DateTimeField(verbose_name='Start matched date')),
                ('end_matched_date', models.DateTimeField(verbose_name='End matched date')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bukhach.CustomGroup', verbose_name='Group')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, max_length=255)),
                ('avatar', models.ImageField(default='def_ava.png', upload_to=bukhach.utils.other_utils.make_filepath, verbose_name='avatar')),
                ('rating', models.FloatField(default=0.0, max_length=2, verbose_name='rating')),
                ('tel_num', models.CharField(blank=True, max_length=21, verbose_name='tel_num')),
                ('friends', models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='bukhach.Profile', verbose_name='friends')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='UserInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('group_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bukhach.CustomGroup', verbose_name='Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
