# Generated by Django 2.0.1 on 2018-01-24 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bukhach', '0002_auto_20180121_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=255)),
                ('avatar', models.ImageField(default='def_ava.png', upload_to='img/avatars', verbose_name='avatar')),
                ('rating', models.FloatField(default=0.0, max_length=2, verbose_name='rating')),
                ('friends', models.ManyToManyField(related_name='_profile_friends_+', to='bukhach.Profile', verbose_name='friends')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
