# Generated by Django 2.0.1 on 2018-02-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukhach', '0005_auto_20180130_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel_num',
            field=models.CharField(blank=True, max_length=21, verbose_name='tel_num'),
        ),
    ]
