# Generated by Django 2.0.1 on 2018-02-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukhach', '0006_auto_20180201_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
