# Generated by Django 2.0.1 on 2018-04-09 11:06

import bukhach.utils.common_utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bukhach', '0007_auto_20180202_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gathering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_avatar', models.ImageField(default='def_group_ava.jpeg', upload_to=bukhach.utils.common_utils.make_filepath, verbose_name='group_avatar')),
                ('group_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='YourGroups', to=settings.AUTH_USER_MODEL, verbose_name='Group creator')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
        ),
        migrations.CreateModel(
            name='GroupApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Applacant')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bukhach.Gathering', verbose_name='Group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_matched_date', models.DateTimeField(verbose_name='Start matched date')),
                ('end_matched_date', models.DateTimeField(verbose_name='End matched date')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bukhach.Gathering', verbose_name='Group')),
            ],
        ),
        migrations.AddField(
            model_name='userinterval',
            name='group_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='bukhach.Gathering', verbose_name='Group'),
        ),
    ]
