# Generated by Django 2.0.1 on 2018-05-24 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bukhach', '0008_auto_20180409_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterval',
            name='gathering_id',
        ),
        migrations.AddField(
            model_name='userinterval',
            name='gathering',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='bukhach.Gathering', verbose_name='Gathering'),
        ),
        migrations.AlterField(
            model_name='gatheringapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Applicant'),
        ),
        migrations.AlterField(
            model_name='gatheringinterval',
            name='gathering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bukhach.Gathering', verbose_name='Gathering'),
        ),
    ]
