# Generated by Django 2.0.1 on 2018-08-02 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bukhach', '0009_auto_20180728_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatheringapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bukhach.Profile', verbose_name='Applicant'),
        ),
    ]
