# Generated by Django 2.0.1 on 2018-08-05 16:12

import bukhach.models.profile_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bukhach', '0011_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='invitationCode',
        ),
        migrations.AddField(
            model_name='invite',
            name='invitation_code',
            field=models.CharField(db_index=True, default=bukhach.models.profile_models.generate_invitation_code, max_length=255),
        ),
        migrations.AlterField(
            model_name='invite',
            name='user',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
