# Generated by Django 2.0.1 on 2018-08-13 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bukhach', '0013_auto_20180805_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatheringinterval',
            name='end_matched_date',
        ),
        migrations.RemoveField(
            model_name='gatheringinterval',
            name='start_matched_date',
        ),
        migrations.AddField(
            model_name='gatheringinterval',
            name='end_date',
            field=models.DateTimeField(default='2018-08-06 20:59:00.000000', verbose_name='End date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gatheringinterval',
            name='start_date',
            field=models.DateTimeField(default='2018-08-06 20:59:00.000000', verbose_name='Start date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invite',
            name='invitation_code',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userinterval',
            name='gathering',
            field=models.ForeignKey(db_column='gathering_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bukhach.Gathering', verbose_name='Gathering'),
        ),
    ]
